### ISSUE TITLE
Coverage for ui-default contains coverage for ui

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#10]
```
gulp test:server -wc --paths=ui-default
```

And I've got:

```
Statements   : 90.37% ( 676/748 )
Branches     : 81.06% ( 261/322 )
Functions    : 95.43% ( 209/219 )
Lines        : 90.19% ( 662/734 )
```

Which is broken because of including ckeditor5-ui's code in the coverage.

**Comment by Reinmar** [comment]
BTW. Sometimes I get 100% :D. So make sure to try couple of times.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/23.
