### ISSUE TITLE
The coverage report isn't precise

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#11]
Sometimes I get some uncovered branches while the report is clear. E.g. for `ckeditor5-undo`. Seems that some integration between Istanbul and Webpack isn't perfect.

**Comment by pomek** [comment]
Are you sure that default parameters are also checked? I had the problem with it in another repository (but I don't remember where).

**Comment by Reinmar** [comment]
Hm... we'd need to investigate each thing separately, but perhaps it's this.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/24.
