### ISSUE TITLE
runTests() hangs after running all tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#17]
E.g. `gulp test:server -c --files=ui`

![image](https://cloud.githubusercontent.com/assets/156149/20104739/6038cea4-a5cf-11e6-8b46-61a902e209f5.png)

It doesn't exit for some reason.

**Comment by Reinmar** [comment]
This is interesting. It works with some test files just find and hangs with other ones ;|

E.g. `gulp test:server -c --files=heading` correctly closed the process.

**Comment by pomek** [comment]
After upgrading Chrome to the latest version, I "reproduced" the issue on CI:

![image](https://cloud.githubusercontent.com/assets/2270764/20743672/f4bb1348-b6d7-11e6-9ac8-1e640972739f.png)

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/25.
