### ISSUE TITLE
Improve stack trace on Travis

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-tests#19]
At this moment, when some test fails on Travis, we have unclear stack trace:

![image](https://cloud.githubusercontent.com/assets/2270764/20134111/6e228546-a66a-11e6-853a-f4955dad52cc.png)

Would be nice to know which assertion has failed.

**Comment by pomek** [comment]
Related issue: https://github.com/litixsoft/karma-mocha-reporter/issues/81

**Comment by Reinmar** [comment]
I debugged this. It turns out that the error happens in mocha's native `onerror` listener. So it has the stack of length 2 and this is quite understandable now that we get this a bit useless error.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/26.
