### ISSUE TITLE
Move `buildEditorsForSamples()` function from main repository

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-tests#2]
Exactly as I mentioned in the title.

At this moment the [`buildEditorsForSamples()`](https://github.com/ckeditor/ckeditor5/blob/docs/gulpfile.js#L160) function is in main repository, in `gulpfile.js`.

[We found](https://github.com/ckeditor/ckeditor5/issues/243#issuecomment-242711654) a better place for her.

**Comment by Reinmar** [comment]
No tests, so there's nothing to validate :). We'll work on this later, when we'll really start using this package. For now, we're not: https://github.com/ckeditor/ckeditor5/pull/324#issuecomment-243726809
