### ISSUE TITLE
Use a more concise Karma reporter on Travis

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#35]
It takes an awful lot of time to scroll down to see why a build has failed. See e.g. https://travis-ci.org/ckeditor/ckeditor5-engine/builds/180348237

**Comment by pomek** [comment]
I understand this issue but I have to ask - are you using the keyboard shortcuts? :D

**Comment by Reinmar** [comment]
Which are?

**Comment by pomek** [comment]
<kbd>Fn</kbd> + <kbd>◄</kbd> = (behaves like Windows) <kbd>Home</kbd> (move your viewport at the top)
<kbd>Fn</kbd> + <kbd>►</kbd> = (behaves like Windows) <kbd>End</kbd> (move your viewport at the bottom)

**Comment by Reinmar** [comment]
The problem isn't scrolling itself. The problem is waiting half a minute while Travis is loading that huge log.

**Comment by pomek** [comment]
I will check this - https://www.npmjs.com/package/karma-super-dots-reporter.

It looks good but I would like to know whether it shows which test fails if Karma fails.

**Comment by pomek** [comment]
Or something similar to the example above.

**Comment by Reinmar** [comment]
Please choose something popular. We don't want to rely on a package which is in 0.1.0 and has 3 stars.

**Comment by pomek** [comment]
I recommend to use preinstalled in Karma `dots` reporter:

![image](https://cloud.githubusercontent.com/assets/2270764/20826392/cb1e21da-b86a-11e6-8b46-8065e36aa631.png)

**Comment by Reinmar** [comment]
Looks fine. Will you add a new option to `gulp test` and related scripts?

**Comment by pomek** [comment]
I would like to detect it based on `process.env.TRAVIS` variable (the same way as we change Chrome).

On local environment, we will have a `mocha` reporter, on CI - `dots`.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-dev-tests/blob/master/lib/utils.js#L241-L243

**Comment by Reinmar** [comment]
I don't think this is the right move. What if I want to run dot reporter locally, cause I don't need the verbose one?

**Comment by pomek** [comment]
Right, but this ticket rather about Karma, not about local environment.
