### ISSUE TITLE
Support tagging manual tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#37]
This is a feature that we haven't ported from Bender, but which was normally useful before a release, during the testing phase. We were able to execute just the manual tests which were important in that specific moment by filtering out tests from previous releases.

OTOH, all manual tests should pass all the time, so perhaps there's no reason to execute just a subset of them.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/27.
