### ISSUE TITLE
The manual test server crashes on 404

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#39]
```
[13:54:40] [Webpack] Finished the compilation.
Error: ENOENT: no such file or directory, open '/www/ckeditor5/ckeditor5/build/.manual-tests/theme/ckeditor.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Server.http.createServer.error (/www/ckeditor5/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-tests/lib/server.js:36:26)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by pomek** [comment]
Could you provide any steps to reproduce?

It looks like the stylesheet is missing but I cannot say anymore without your help.

**Comment by Reinmar** [comment]
I had a problem when CSS didn't build because of some error in SCSS files. You can try this. But... if it happened for all files it would always happen because of missing favicon. Strange.

**Comment by pomek** [comment]
We assume that CSS file will always exist - https://github.com/ckeditor/ckeditor5-dev-tests/blob/master/lib/server.js#L35-L39

In other cases, the server will return HTTP Error 500 - https://github.com/ckeditor/ckeditor5-dev-tests/blob/master/lib/server.js#L47-L56.

As you mentioned:

> I had a problem when CSS didn't build because of some error in SCSS files.

This is the reason why server crashed. We can introduce additional protection but… if css task in Compiler threw an error, the whole compiler should reject a promise and the server should never start. Am I right?

**Comment by Reinmar** [comment]
Why can't this file be served by the try-catch which is later on? The code should be refactored in that function so all files (which are sourced from the file system) are handled there.

**Comment by pomek** [comment]
We can. As I mentioned above, I assumed that CSS file will be always available. I will change it.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/29.
