### ISSUE TITLE
Karma server isn't serving source maps for automated tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#41]
After we switched to separate source maps in https://github.com/ckeditor/ckeditor5-dev-tests/issues/40 source maps don't work in automated tests.

```
18 12 2016 21:39:24.068:WARN [web-server]: 404: /base/tests/engine/model/schema/schema.js.map
```

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/30.
