### ISSUE TITLE
Rename the --paths option to --files and allow globs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#6]
To be consistent with other projects.

**Comment by Reinmar** [comment]
Edit: This option should work like a glob pattern.

**Comment by pomek** [comment]
Fixes by: #12.

**Comment by Reinmar** [comment]
This isn't fixed. There's still a problem with:

```
(master 9256354) oleq@Aleksanders-MBP ~/CK/5/ckeditor5> gulp test:server --paths=ui/**/*.js
```

**Comment by Reinmar** [comment]
Actually, @oleq might've been using v1.0.0 still. Let's see for him to confirm that after update it will work.

**Comment by Reinmar** [comment]
Confirmed. It's working fine.
