### ISSUE TITLE
Allow to save karma.conf.js file

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-dev-tests#8]
Due to project's constrains the `karma.conf.js` is generated on the fly during tests.

To allow integration with tools that uses `karma.conf.js` file it would nice to save generated on the fly config file.

Proposed solution add an option to save `karma.conf.js`, ie:
- add command line option: `--save-karma-conf` or `--save` that will save generated config file.
- optionally one would like to provide a name for generated config file, ie.: to have different configurations for different purposes (as you can use different configs for tests)

This will allow other tools to use that config, ie PHP/WebStorm Karma plugin uses `karma.conf.js` file to run test and displays results and code coverage.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/21.
