### ISSUE TITLE
Webpack memory leaks

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-tests#9]
I can see that this is a pretty popular issue: https://github.com/webpack/webpack/labels/S3%3A%20Memory%20Leak.

Let's keep track of what happens with them.

**Comment by Reinmar** [comment]
We can also check https://github.com/webpack/karma-webpack#alternative-usage.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/22.
